### ISSUE TITLE
Database structure does not support high decimal latitudes

### ISSUE THREAD

**Issue by TimoWinkler** [nimius/location-manager#4]
On importing a database table into tx_locationmanager_domain_model_location we discovered, that latitude does expect the type decimal(10,8) and longitude the type decimal(11,8).
You cannot enter a latitude of the following form: xxx.xxxxxxx.

**Comment by j6s** [comment]
The database design is restrictive by design.

Latitude has a value range of -90 to 90 whereas longitude has a value range of -180 to 180.
The database definition reflects that range of possible values.

More information / reference:
- https://developers.google.com/maps/documentation/javascript/reference#LatLng
- https://msdn.microsoft.com/en-us/library/aa578799.aspx

If you have latitude data in a value range of 0 to 180 you have to transform it to fit the -90 to 90 value range while importing.
